sudo: false
language: bash
os:
  - linux

addons:
  apt:
    packages:
      - python
      - python-serial
      - gperf

before_install:
  - PROJECT_PATH=$(pwd)

install:
  - mkdir -p ~/esp
  - cd ~/esp
  - wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-61-gab8375a-5.2.0.tar.gz
  - tar -xzf xtensa-esp32-elf-linux64-1.22.0-61-gab8375a-5.2.0.tar.gz
  - export PATH=$PATH:$HOME/esp/xtensa-esp32-elf/bin
  - git clone --recursive https://github.com/espressif/esp-idf.git
  - export IDF_PATH=~/esp/esp-idf

script:
  - cd $PROJECT_PATH
  - make defconfig
  - make all